/**
 * resetAndImportCentrepitch15Players.js
 *
 * Purpose:
 * - Keep the existing superadmin user(s)
 * - Wipe CentrePitch match/event data + CA-1 analytics_* collections
 * - Import CA-1-style synthetic dataset (centrepitch_15players.json) into:
 *    - CentrePitch: users, players, sports academy, coach + relations, events + schedule matches, matchstats
 *    - Analytics: regenerated by ingesting each match into CA-1 via existing ingestMatchAnalytics bridge
 *
 * Notes:
 * - The JSON uses synthetic IDs (PLR-BDM-xxx, MTH-BDM-...) which are NOT Mongo ObjectIds.
 *   We store them as external IDs on users for traceability, and generate real ObjectId references.
 * - CA-1 stores ids as strings; join keys back to CentrePitch are persisted as strings too.
 *
 * Usage:
 *   node --env-file=.env scripts/resetAndImportCentrepitch15Players.js
 */

import fs from 'node:fs';
import path from 'node:path';
import mongoose from 'mongoose';
import dotenv from 'dotenv';

import User from '../models/User.js';
import Player from '../models/Player.js';
import Sport from '../models/Sport.js';
import Event from '../models/Event.js';
import MatchStat from '../models/MatchStat.js';
import SportsAcademy from '../models/SportsAcademy.js';
import Coach from '../models/Coach.js';
import UserSport from '../models/UserSport.js';
import CoachStudentRelation from '../models/CoachStudentRelation.js';

import { ingestMatchAnalytics } from '../services/analyticsService.js';

dotenv.config();

const MONGO_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/centre_pitch';
const IMPORT_PASSWORD = process.env.IMPORT_PASSWORD || 'Import@1234';

const JSON_PATH =
  process.env.IMPORT_JSON_PATH ||
  '/Users/apple/Desktop/GVCC-Application/CA-1/centrepitch_15players.json';

const toDate = (yyyyMmDd) => new Date(`${yyyyMmDd}T10:00:00.000Z`);

/** User.email regex only allows TLD segments of 2–3 chars (e.g. .com). Avoid .local etc. */
const IMPORT_EMAIL_DOMAIN = process.env.IMPORT_EMAIL_DOMAIN || 'seed.centrepitch.com';

function safeEmailFromExternalId(externalId) {
  const slug = String(externalId || '').toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return `${slug}@${IMPORT_EMAIL_DOMAIN}`;
}

function nameFromExternalId(externalId) {
  // PLR-BDM-004 -> Player 004
  const m = String(externalId || '').match(/(\d+)\s*$/) || String(externalId || '').match(/-(\d+)$/);
  const n = m ? m[1].padStart(3, '0') : '000';
  return { firstName: 'Player', lastName: n };
}

async function deleteAnalyticsCollections(db) {
  const cols = await db.listCollections().toArray();
  const analyticsCols = cols
    .map((c) => c.name)
    .filter((n) => n.startsWith('analytics_'));

  for (const name of analyticsCols) {
    await db.collection(name).deleteMany({});
  }
  return analyticsCols;
}

async function ensureBadmintonSport(superadminId) {
  const existing = await Sport.findOne({ slug: 'badminton' }).lean();
  if (existing) return existing;

  const sport = await Sport.create({
    name: 'Badminton',
    description: 'Imported dataset sport',
    scope: 'platform',
    isActive: true,
    isFeatured: true,
    formats: {
      individual: { enabled: true, minPlayers: 1, maxPlayers: 1, description: 'Singles' },
      doubles: { enabled: true, minPlayers: 2, maxPlayers: 2, description: 'Doubles' },
      team: { enabled: false, minPlayersPerTeam: 5, maxPlayersPerTeam: 15, playingCount: 11, substitutesCount: 4, description: '' },
    },
    createdBy: superadminId || null,
    updatedBy: superadminId || null,
  });

  return sport.toObject();
}

async function main() {
  await mongoose.connect(MONGO_URI);
  console.log('Connected:', MONGO_URI);

  const db = mongoose.connection.db;

  const superadmins = await User.find({ role: 'superadmin' }).select('_id email').lean();
  if (superadmins.length === 0) {
    throw new Error('No superadmin found. Create one first (bootstrap) before running reset/import.');
  }
  const superadminId = superadmins[0]._id;
  console.log('Keeping superadmin(s):', superadmins.map((u) => u.email || String(u._id)));

  // ─── Wipe application data (except superadmin users) ──────────────────────

  const usersToDelete = await User.find({ role: { $ne: 'superadmin' } }).select('_id').lean();
  const userIdsToDelete = usersToDelete.map((u) => u._id);

  await Promise.all([
    Event.deleteMany({}),
    MatchStat.deleteMany({}),
    Player.deleteMany({}),
    CoachStudentRelation.deleteMany({}),
    UserSport.deleteMany({}),
    Coach.deleteMany({ userId: { $in: userIdsToDelete } }),
    SportsAcademy.deleteMany({}),
    User.deleteMany({ _id: { $in: userIdsToDelete } }),
  ]);

  const clearedAnalyticsCols = await deleteAnalyticsCollections(db);
  console.log('Cleared analytics collections:', clearedAnalyticsCols.join(', ') || '(none)');

  // ─── Load JSON dataset ────────────────────────────────────────────────────

  const raw = fs.readFileSync(JSON_PATH, 'utf-8');
  const dataset = JSON.parse(raw);
  const externalPlayers = Array.isArray(dataset?.players) ? dataset.players : [];
  const externalMatches = Array.isArray(dataset?.matches) ? dataset.matches : [];

  if (externalPlayers.length === 0 || externalMatches.length === 0) {
    throw new Error('Import JSON has no players or matches.');
  }

  // ─── Create baseline entities: sport, academy, users by role ──────────────

  const sport = await ensureBadmintonSport(superadminId);

  // organizer
  const organizerUser = await User.create({
    firstName: 'Org',
    lastName: 'User',
    email: `organizer@${IMPORT_EMAIL_DOMAIN}`,
    phone: '+910000000001',
    password: IMPORT_PASSWORD,
    role: 'organizer',
    activeRole: 'organizer',
    baseRole: 'organizer',
    organizationName: 'Imported Organizer',
    organizerSports: [sport._id],
    isActive: true,
    isVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
  });

  // academy admin + academy
  const academyAdminUser = await User.create({
    firstName: 'Academy',
    lastName: 'Admin',
    email: `academyadmin@${IMPORT_EMAIL_DOMAIN}`,
    phone: '+910000000002',
    password: IMPORT_PASSWORD,
    role: 'academyadmin',
    activeRole: 'academyadmin',
    baseRole: 'academyadmin',
    isActive: true,
    isVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
  });

  const academy = await SportsAcademy.create({
    name: 'Imported Academy',
    description: 'Academy created by import script',
    email: `academy@${IMPORT_EMAIL_DOMAIN}`,
    phone: '+910000000003',
    status: 'APPROVED',
    kycStatus: 'VERIFIED',
    isActive: true,
    adminUser: academyAdminUser._id,
    sportsOffered: [sport._id],
    address: { city: 'Bengaluru', country: 'India' },
  });

  academyAdminUser.academyId = academy._id;
  await academyAdminUser.save();

  // coach user + coach profile
  const coachUser = await User.create({
    firstName: 'Coach',
    lastName: 'One',
    email: `coach@${IMPORT_EMAIL_DOMAIN}`,
    phone: '+910000000004',
    password: IMPORT_PASSWORD,
    role: 'coach',
    activeRole: 'coach',
    baseRole: 'coach',
    isActive: true,
    isVerified: true,
    isEmailVerified: true,
    isPhoneVerified: true,
  });

  const coachProfile = await Coach.create({
    userId: coachUser._id,
    firstName: coachUser.firstName,
    lastName: coachUser.lastName,
    email: coachUser.email,
    phone: coachUser.phone,
    dateOfBirth: new Date('1990-01-01T00:00:00.000Z'),
    gender: 'MALE',
    coachType: 'ACADEMY_COACH',
    academies: [{ academy: academy._id, status: 'APPROVED' }],
    specialization: [sport._id],
    status: 'APPROVED',
    kycStatus: 'VERIFIED',
  });

  coachUser.coachProfile = coachProfile._id;
  await coachUser.save();

  // ─── Create 15 player users + player profiles + sport bindings ────────────

  const externalToUserId = new Map();
  const externalToPlayerDocId = new Map();
  const externalToUserSportId = new Map();

  // NOTE: In this backend, `UserSport` is a global sport dictionary model (requires `name`),
  // not a per-user binding. Create/reuse a single entry and reference it where needed.
  const badmintonUserSport = await UserSport.findOneAndUpdate(
    { slug: 'badminton', scope: 'system' },
    {
      $setOnInsert: {
        name: 'Badminton',
        scope: 'system',
        isActive: true,
        createdBy: superadminId,
      },
    },
    { new: true, upsert: true },
  );

  for (const p of externalPlayers) {
    const extId = String(p?.id || '').trim();
    if (!extId) continue;

    const { firstName, lastName } = nameFromExternalId(extId);
    const email = safeEmailFromExternalId(extId);

    const user = await User.create({
      firstName,
      lastName,
      email,
      phone: '',
      password: IMPORT_PASSWORD,
      role: 'player',
      activeRole: 'player',
      baseRole: 'player',
      isActive: true,
      isVerified: true,
      isEmailVerified: true,
      isPhoneVerified: true,
      // keep external mapping for traceability
      description: `externalPlayerId=${extId}`,
    });

    externalToUserId.set(extId, user._id);

    const player = await Player.create({
      user: user._id,
      name: `${firstName} ${lastName}`.trim(),
      email: user.email,
      academies: [academy._id],
      sports: [{ sport: sport._id, sportName: 'Badminton', level: 'intermediate' }],
      status: 'active',
      isActive: true,
    });
    externalToPlayerDocId.set(extId, player._id);
    externalToUserSportId.set(extId, badmintonUserSport._id);
  }

  // Coach scope relations: make first 8 players "active students"
  const studentExtIds = [...externalToUserId.keys()].slice(0, 8);
  for (const extId of studentExtIds) {
    await CoachStudentRelation.create({
      coach: coachProfile._id,
      player: externalToPlayerDocId.get(extId),
      sport: externalToUserSportId.get(extId),
      sportName: 'Badminton',
      academy: academy._id,
      status: 'active',
      source: 'academy_assigned',
      startedAt: new Date(),
      reviewedBy: superadminId,
      reviewedAt: new Date(),
    });
  }

  // ─── Create many events (group by match.date) + matches + matchstats ───────

  const matchesByDate = new Map();
  for (const m of externalMatches) {
    const d = String(m?.date || '').trim();
    if (!d) continue;
    (matchesByDate.get(d) || matchesByDate.set(d, []).get(d)).push(m);
  }

  let createdEvents = 0;
  let createdMatches = 0;

  for (const [dateStr, matches] of matchesByDate.entries()) {
    const start = toDate(dateStr);
    const end = toDate(dateStr);

    const event = await Event.create({
      name: `[IMPORT] ${dataset?.sport?.name || 'Badminton'} ${dateStr}`,
      description: 'Imported event from centrepitch_15players.json',
      sport: sport._id,
      eventType: 'badminton',
      gameFormat: 'individual',
      eventTypeId: dataset?.sport?.id || undefined,
      startDate: start,
      endDate: end,
      registrationStartDate: start,
      registrationEndDate: end,
      organizer: organizerUser._id,
      status: 'completed',
      location: { venue: 'Imported Venue', city: 'Bengaluru', country: 'India' },
      schedule: [{ round: 'Main', matches: [] }],
    });

    createdEvents += 1;

    const round = event.schedule[0];

    for (const m of matches) {
      const extA = String(m?.player_a?.id || '').trim();
      const extB = String(m?.player_b?.id || '').trim();
      const userAId = externalToUserId.get(extA);
      const userBId = externalToUserId.get(extB);
      if (!userAId || !userBId) continue;

      const winnerExt = String(m?.match_winner || '').trim();
      const winnerUserId = externalToUserId.get(winnerExt) || userAId;

      round.matches.push({
        matchNumber: createdMatches + 1,
        player1: userAId,
        player2: userBId,
        dateTime: toDate(dateStr),
        venue: 'Court 1',
        result: {
          winner: winnerUserId,
          score: `${m?.sets_won?.player_a ?? 0}-${m?.sets_won?.player_b ?? 0}`,
          status: 'completed',
        },
      });
      createdMatches += 1;
    }

    await event.save();

    // For each match, write MatchStat docs and ingest to CA-1
    for (const match of event.schedule[0].matches) {
      const userAId = match.player1;
      const userBId = match.player2;

      const userA = await User.findById(userAId).select('firstName lastName').lean();
      const userB = await User.findById(userBId).select('firstName lastName').lean();
      const nameA = `${userA?.firstName || ''} ${userA?.lastName || ''}`.trim() || String(userAId);
      const nameB = `${userB?.firstName || ''} ${userB?.lastName || ''}`.trim() || String(userBId);

      // Find external match by date + participants
      const extMatch = matches.find((mm) => {
        const a = String(mm?.player_a?.id || '');
        const b = String(mm?.player_b?.id || '');
        const ua = externalToUserId.get(a);
        const ub = externalToUserId.get(b);
        return ua && ub && String(ua) === String(userAId) && String(ub) === String(userBId);
      });

      const teamTotals = extMatch
        ? {
            points: (extMatch.sets || []).flatMap((s) =>
              (s.points || []).map((pt) => ({
                point_id: pt.point_id,
                set_number: s.set_number,
                score_before: pt.score_before,
                point_winner: externalToUserId.get(pt.point_winner) ? String(externalToUserId.get(pt.point_winner)) : String(userAId),
                server: externalToUserId.get(pt.server) ? String(externalToUserId.get(pt.server)) : String(userAId),
                rally_shots: pt.rally_shots,
                rally_duration_sec: pt.rally_duration_sec,
                ending_type: pt.ending_type,
              })),
            ),
            sets: (extMatch.sets || []).map((s) => ({
              set_number: s.set_number,
              score_a: s.score?.player_a ?? 0,
              score_b: s.score?.player_b ?? 0,
              winner: externalToUserId.get(s.winner) ? String(externalToUserId.get(s.winner)) : String(userAId),
              is_deuce: !!s.is_deuce,
            })),
          }
        : {};

      await MatchStat.findOneAndUpdate(
        { event: event._id, matchId: match._id, 'participant.type': 'player', 'participant.refId': userAId },
        {
          $set: {
            event: event._id,
            matchId: match._id,
            participant: { type: 'player', refId: userAId, name: nameA },
            teamTotals,
            lastUpdatedBy: organizerUser._id,
          },
        },
        { upsert: true },
      );

      await MatchStat.findOneAndUpdate(
        { event: event._id, matchId: match._id, 'participant.type': 'player', 'participant.refId': userBId },
        {
          $set: {
            event: event._id,
            matchId: match._id,
            participant: { type: 'player', refId: userBId, name: nameB },
            teamTotals: {},
            lastUpdatedBy: organizerUser._id,
          },
        },
        { upsert: true },
      );

      await ingestMatchAnalytics(event, match);
    }
  }

  console.log(`Imported: ${externalToUserId.size} players, ${createdEvents} events, ${createdMatches} matches.`);
  console.log('Role users created:', {
    organizer: organizerUser.email,
    academyadmin: academyAdminUser.email,
    coach: coachUser.email,
    superadmin_kept: superadmins[0].email || String(superadmins[0]._id),
  });
  console.log('Default password for imported users:', IMPORT_PASSWORD);

  await mongoose.disconnect();
}

main().catch(async (err) => {
  console.error('Import failed:', err);
  await mongoose.disconnect();
  process.exit(1);
});

